name = "kronos-novels"
compatibility_date = "2024-01-01"

[env.production]
name = "kronos-novels"
routes = [
  { pattern = "kronos-novels.pages.dev/api/*", zone_name = "kronos-novels.pages.dev" }
]

# Environment variables (set via Cloudflare dashboard)
# GITHUB_CLIENT_ID = "your_github_client_id"
# GITHUB_CLIENT_SECRET = "your_github_client_secret"
# UPLOADTHING_TOKEN = "eyJhcGlLZXkiOiJza19saXZlXzlhNjQ2MWFlYTZhNTkyYTQ5ZGVmMTAwZTZmYzBiNzdiZDE3NzVlMTY2M2U3MzIwYTU0NjI2MjdjOGU0MWE3MzciLCJhcHBJZCI6ImdrdzV5MHM0MmUiLCJyZWdpb25zIjpbInNlYTEiXX0="
